sudo: required
language: rust
rust:
  - 1.0.0
  - beta
  - nightly
install:
  - sudo apt-get install cmake
  - git clone https://github.com/BYVoid/OpenCC.git && cd OpenCC
  - make && sudo make install
  - sudo ldconfig
  - cd ..
script:
  - cargo build --verbose
  - cargo test --verbose
